# Generated by Django 5.2.8 on 2025-12-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('announcement_type', models.CharField(choices=[('event', 'Event'), ('notice', 'Notice'), ('update', 'Update'), ('alert', 'Alert')], default='notice', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/files/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('target_roles', models.JSONField(blank=True, help_text='Optional list of roles this announcement is visible to (student, teacher, admin)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
