# Generated by Django 5.2.8 on 2025-12-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('academic_level', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=10)),
                ('semester', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=50)),
                ('upload_type', models.CharField(choices=[('report', 'Report'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('cart', 'Cart')], max_length=20)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resources/%Y/%m/%d/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='resources.resourceupload')),
            ],
        ),
    ]
